export const AlertEvents = [
    { code: 'DSW', name: 'Dust Storm Warning' },
    { code: 'FAY', name: 'Flood Watch' },
    { code: 'FAW', name: 'Flood Warning' },
    { code: 'FFS', name: 'Flash Flood Statement' },
    { code: 'FFW', name: 'Flash Flood Warning' },
    { code: 'FFA', name: 'Flash Flood Watch' },
    { code: 'GLW', name: 'Gale Warning' },
    { code: 'GLA', name: 'Gale Watch' },
    { code: 'HFW', name: 'Hurricane Force Wind Warning' },
    { code: 'HFA', name: 'Hurricane Force Wind Watch' },
    { code: 'HUW', name: 'Hurricane Warning' },
    { code: 'HUA', name: 'Hurricane Watch' },
    { code: 'ISW', name: 'Ice Storm Warning' },
    { code: 'LEW', name: 'Lake Effect Snow Warning' },
    { code: 'SWS', name: 'Special Weather Statement' },
    { code: 'SMW', name: 'Special Marine Warning' },
    { code: 'SVW', name: 'Severe Thunderstorm Warning' },
    { code: 'SVA', name: 'Severe Thunderstorm Watch' },
    { code: 'TOW', name: 'Tornado Warning', colour: '' },
    { code: 'TOA', name: 'Tornado Watch' }
];
